# Estados de Registro
(TIPO, VALOR, CATEGORIA, INSTITUICAO, DESCRICAO, 
 PRODUTO, TIPO_INVEST, VENCIMENTO, INDICADOR, DATA_INICIO, DATA_FIM) = range(11)

# Estados de Consulta
CONS_TIPO, CONS_INSTITUICAO = range(11, 13)